project:
  output-dir: renders
  pre-render: functions\n3_data_preprocessing.R
  render:
    - mapping_n3_dt_basin_builder.qmd
    - mapping_n3_generate_docx.qmd

toc: true
toc-location: left
number-sections: true

format:
  html:
    code-fold: true
    code-overflow: wrap
    code-tools: true
    embed-resources: true
    standalone: true
    theme: flatly
  docx: default
execute: 
  warning: false

