project:
  output-dir: renders
  pre-render: functions\n3_data_preprocessing.R
  render:
    - mapping_n3_basin_builder.qmd
    - mapping_n3_basin_grades.qmd
    - mapping_n3_dem.qmd
    - mapping_n3_generate_docx.qmd
    - mapping_n3_regional_ecosystems.qmd
    
toc: true
toc-location: left
number-sections: true

format:
  html:
    code-fold: true
    code-overflow: wrap
    code-tools: true
    embed-resources: true
    standalone: true
    theme: flatly
  docx:
    reference-doc: functions\custom-reference-doc.docx
execute: 
  warning: false

